=== de-bund-bsi-tr-esor/tr-esor-AIP-eIDAS-SigValidator/aip-validator-api/src/main/resources/wsdl/tr-esor-xaip-v1.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xaip="http://www.bsi.bund.de/tr-esor/xaip" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" xmlns:ers="urn:ietf:params:xml:ns:ers" xmlns:vr="urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#" xmlns:dss="urn:oasis:names:tc:dss:1.0:core:schema" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" targetNamespace="http://www.bsi.bund.de/tr-esor/xaip" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.3.0">
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="./deps/xmldsig-core-schema.xsd"/>
	<xs:import namespace="http://uri.etsi.org/01903/v1.3.2#" schemaLocation="./deps/XAdES01903v132-201601.xsd"/>
	<xs:import namespace="urn:ietf:params:xml:ns:ers" schemaLocation="./deps/xml-ers-rfc6283.xsd"/>
	<xs:import namespace="urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#" schemaLocation="./deps/oasis-dssx-1.0-profiles-verification-report-cs1.xsd"/>
	<xs:import namespace="urn:oasis:names:tc:dss:1.0:core:schema" schemaLocation="./deps/oasis-dss-core-schema-v1.0-os.xsd"/>
	<xs:import namespace="urn:oasis:names:tc:SAML:2.0:assertion" schemaLocation="./deps/saml-schema-assertion-2.0.xsd"/>
	<xs:import namespace="http://www.w3.org/2005/05/xmlmime" schemaLocation="./deps/xmlmime.xsd"/>
	<!--============================================================ -->
	<!-- Version 1.3.0 vom 14.03.2022 -->
	<!--============================================================ -->
	<!--============================================================ -->
	<!-- XAIP gesamt -->
	<!--============================================================ -->
	<xs:element name="XAIP" type="xaip:XAIPType"/>
	<xs:complexType name="XAIPType">
		<xs:sequence>
			<xs:element name="packageHeader" type="xaip:packageHeaderType"/>
			<xs:element name="metaDataSection" type="xaip:metaDataSectionType" minOccurs="0"/>
			<xs:element name="dataObjectsSection" type="xaip:dataObjectsSectionType" minOccurs="0"/>
			<xs:element name="credentialsSection" type="xaip:credentialsSectionType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="XAIPVersion" use="required" fixed="1.3.0"/>
	</xs:complexType>
	<!--============================================================ -->
	<!-- packageHeaderType -->
	<!--============================================================ -->
	<xs:complexType name="packageHeaderType">
		<xs:sequence>
			<xs:element name="AOID" type="xs:string" minOccurs="0"/>
			<xs:element name="packageInfo" type="xs:string" minOccurs="0"/>
			<xs:element name="versionManifest" type="xaip:versionManifestType" maxOccurs="unbounded"/>
			<xs:element ref="ds:CanonicalizationMethod" minOccurs="0"/>
			<xs:element name="extension" type="xaip:extensionType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="packageID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="extensionType">
		<xs:sequence>
			<xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="versionManifestType">
		<xs:sequence>
			<xs:element name="versionInfo" type="xs:string" minOccurs="0"/>
			<xs:element name="preservationInfo" type="xaip:preservationInfoType"/>
			<xs:element name="submissionInfo" type="xaip:submissionInfoType" minOccurs="0"/>
			<xs:element name="packageInfoUnit" type="xaip:packageInfoUnitType" maxOccurs="unbounded"/>
			<xs:element ref="xaip:idAssignmentList" minOccurs="0"/>
			<xs:element name="extension" type="xaip:extensionType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="VersionID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="preservationInfoType">
		<xs:sequence>
			<xs:element name="retentionPeriod" type="xs:date"/>
			<xs:element name="status" type="xs:string" minOccurs="0"/>
			<xs:element name="extension" type="xaip:extensionType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="submissionInfoType">
		<xs:sequence>
			<xs:element name="clientID" type="saml:NameIDType"/>
			<xs:element name="submissionUnit" type="saml:NameIDType" minOccurs="0"/>
			<xs:element name="submissionAuthor" type="saml:NameIDType" minOccurs="0"/>
			<xs:element name="submissionTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="extension" type="xaip:extensionType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="packageInfoUnitType">
		<xs:sequence>
			<xs:element name="unitType" type="xs:string" minOccurs="0"/>
			<xs:element name="textInfo" type="xs:string" minOccurs="0"/>
			<xs:element name="protectedObjectPointer" type="xs:IDREF" maxOccurs="unbounded"/>
			<xs:element name="unprotectedObjectPointer" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="packageInfoUnit" type="xaip:packageInfoUnitType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="extension" type="xaip:extensionType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="packageUnitID" type="xs:ID" use="required"/>
	</xs:complexType>
	<!--============================================================ -->
	<!-- MetadataSection -->
	<!--============================================================ -->
	<xs:complexType name="metaDataSectionType">
		<xs:sequence>
			<xs:element ref="xaip:metaDataObject" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="metaDataObject" type="xaip:metaDataObjectType"/>
	<xs:complexType name="metaDataObjectType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="xaip:binaryMetaData"/>
				<xs:element name="xmlMetaData" type="dss:AnyType"/>
			</xs:choice>
			<xs:element ref="xaip:checkSum" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="metaDataID" type="xs:ID" use="required"/>
		<xs:attribute name="relatedObjects" type="xs:IDREFS" use="required"/>
		<xs:attribute name="category" type="xs:string"/>
		<xs:attribute name="classification" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
	<xs:element name="binaryMetaData" type="xaip:binaryMetaDataType"/>
	<xs:complexType name="binaryMetaDataType" xmime:expectedContentTypes="*/*">
		<xs:simpleContent>
			<xs:extension base="xs:base64Binary">
				<xs:attribute name="MimeType" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!--============================================================ -->
	<!-- DataObjectsSection -->
	<!--============================================================ -->
	<xs:complexType name="dataObjectsSectionType">
		<xs:sequence>
			<xs:element ref="xaip:dataObject" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="binaryData" type="xaip:binaryDataType"/>
	<xs:complexType name="binaryDataType" xmime:expectedContentTypes="*/*">
		<xs:simpleContent>
			<xs:extension base="xs:base64Binary">
				<xs:attribute name="MimeType" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="dataObject" type="xaip:dataObjectType"/>
	<xs:complexType name="dataObjectType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="xaip:binaryData"/>
				<xs:element name="xmlData" type="dss:AnyType"/>
			</xs:choice>
			<xs:element ref="xaip:checkSum" minOccurs="0"/>
			<xs:element name="transformInfo" type="xaip:tranformInfoType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="dataObjectID" type="xs:ID" use="required"/>
		<xs:attribute name="relatedObjects" type="xs:IDREFS"/>
	</xs:complexType>
	<xs:element name="checkSum" type="xaip:checkSumType"/>
	<xs:complexType name="checkSumType">
		<xs:sequence>
			<xs:element name="checkSumAlgorithm" type="xs:anyURI"/>
			<xs:element name="checkSum" type="xs:hexBinary"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="tranformInfoType">
		<xs:sequence>
			<xs:element name="transformObject" type="xaip:transformObjectType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="transformObjectType">
		<xs:sequence>
			<xs:element name="transformAlgorithm" type="xs:anyURI"/>
			<xs:element name="Parameters" type="xs:anyType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="transformObjectID" type="xs:ID" use="required"/>
		<xs:attribute name="order" type="xs:string"/>
	</xs:complexType>
	<!--============================================================ -->
	<!-- CredentialsSection -->
	<!--============================================================ -->
	<xs:complexType name="credentialsSectionType">
		<xs:sequence>
			<xs:element ref="xaip:credential" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="credential" type="xaip:credentialType"/>
	<xs:complexType name="credentialType">
		<xs:choice>
			<xs:element ref="dss:SignatureObject"/>
			<xs:element name="certificateValues" type="xades:CertificateValuesType"/>
			<xs:element name="revocationValues" type="xades:RevocationValuesType"/>
			<xs:element ref="xaip:evidenceRecord"/>
			<xs:element ref="vr:VerificationReport"/>
			<xs:element name="other" type="xaip:extensionType"/>
		</xs:choice>
		<xs:attribute name="relatedObjects" type="xs:IDREFS"/>
		<xs:attribute name="credentialID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:element name="evidenceRecord" type="xaip:EvidenceRecordType"/>
	<xs:complexType name="EvidenceRecordType">
		<xs:choice>
			<xs:element name="xmlEvidenceRecord" type="ers:EvidenceRecordType"/>
			<xs:element name="asn1EvidenceRecord" type="xs:base64Binary"/>
		</xs:choice>
		<xs:attribute name="AOID" type="xs:string"/>
		<xs:attribute name="VersionID" type="xs:string"/>
	</xs:complexType>
	<!--============================================================ -->
	<!-- Delta-XAIP -->
	<!--============================================================ -->
	<xs:element name="DXAIP" type="xaip:DXAIPType"/>
	<xs:complexType name="DXAIPType">
		<xs:complexContent>
			<xs:extension base="xaip:XAIPType">
				<xs:sequence>
					<xs:element name="updateSection" type="xaip:updateSectionType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="updateSectionType">
		<xs:sequence>
			<xs:element name="prevVersion" type="xs:string"/>
			<xs:element name="placeHolder" type="xaip:placeHolderType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="placeHolderType">
		<xs:attribute name="objectID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:element name="idAssignmentList" type="xaip:idAssignmentListType"/>
	<xs:complexType name="idAssignmentListType">
		<xs:sequence>
			<xs:element ref="xaip:idAssignmentPointer" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="idAssignmentListID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:element name="idAssignmentPointer" type="xaip:idAssignmentPointerType"/>
	<xs:complexType name="idAssignmentPointerType">
		<xs:sequence>
			<xs:element ref="xaip:checkSum"/>
		</xs:sequence>
		<xs:attribute name="objectRef" type="xs:IDREF" use="required"/>
	</xs:complexType>
</xs:schema>

=== de-bund-bsi-tr-esor/tr-esor-AIP-eIDAS-SigValidator/aip-validator-cli/src/test/resources/cases/XAIP13-asice-tsp-det-single.xml
<?xml version="1.0" encoding="UTF-8"?>
<esor:XAIP xmlns:esor="http://www.bsi.bund.de/tr-esor/xaip" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:dss="urn:oasis:names:tc:dss:1.0:core:schema" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bsi.bund.de/tr-esor/xaip file:///C:/Projects/BSI/Proc-XAIPSigVal/60.Abnahme/220106-cli/211130-TR-ESOR-Schema-1.3.0/tr-esor-xaip-v1.3.xsd" XAIPVersion="1.3.0">
	<esor:packageHeader packageID="x373f4e59-69dc-4a77-9ea6-75e91a74bfc4">
		<esor:AOID>40387ca1-4497-40fa-acfa-9976132b1001</esor:AOID>
		<esor:versionManifest VersionID="V001">
			<esor:preservationInfo>
				<esor:retentionPeriod>2100-01-01+01:00</esor:retentionPeriod>
			</esor:preservationInfo>
			<esor:submissionInfo>
				<esor:clientID>remotebean_esor12</esor:clientID>
				<esor:submissionTime>2022-02-10T14:43:26.898+01:00</esor:submissionTime>
			</esor:submissionInfo>
			<esor:packageInfoUnit packageUnitID="_idx_DO-01_V001">
				<esor:protectedObjectPointer>CR-01</esor:protectedObjectPointer>
			</esor:packageInfoUnit>
		</esor:versionManifest>
		<ds:CanonicalizationMethod xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
	</esor:packageHeader>
	<esor:credentialsSection>
		<esor:credential credentialID="CR-01">
			<dss:SignatureObject>
				<!-- ASiC-E with single detached TSP and mimetype -->
				<dss:Base64Signature>UEsDBAoAAAgAAARdVVSKIflFHwAAAB8AAAAIAAAAbWltZXR5cGVhcHBsaWNhdGlvbi92bmQuZXRzaS5hc2ljLWUremlwUEsDBBQACAgIAARdVVQyugebjwAAAKwAAAALAAAAdGVzdC0wMS50eHQtjTEOgkAQRXsS7jAlFBpcY2MJNrTiBTYw7E6Q2c3sEMLdLURi+/Lff3lWLzxgsrPC+BHoqPcoHkmBGAYUaHkMMlulwEmx90wTFHXXlnmWZ6/nqbpezO0ONa5IaUXRXbdvXdjBJFvU4MRGT6n3kMgxHQt4hGmZkRWPF0w6/MH5B5oQNyHnFfYQFE0JpjLmC1BLBwgyugebjwAAAKwAAABQSwMEFAACAAgAI3g6VB4OGwvlAAAAcAEAABUAAAAwMDItdGVzdC1kb2N1bWVudC54bWx9kEFLw0AQhc8K/odhT3rINlkRJCQptEEQ9GJT8Jpmx3QwncjsRvS/efOPuTFozcXrm/e9x7xs+Xbo4BXFUc+5SnSsALnpLXGbq211E12rZXF2mrFL0gqdL2uPDAFilwYtV4NQunOkdwNbbVF7iS8Tc6V9MKtAnkwoeeyK6iH6PsKYZPvn4YDss8XR8GNfoWv2ghRC26KsHZDzgMQzEJ4+PwQsIZS1uIB3wQ0WBR7v76INtVz7QZD11DDLnIpMuu5f3oXavf99yfz/km5EFUfqfH0Bq80tmNjEY82fxHG1xWy2oHwBUEsDBBQAAgAIAFlwVVQ8GjWOkAEAAJADAAAZAAAATUVUQS1JTkYvQVNpQ01hbmlmZXN0LnhtbNWTXW/aMBSG/0pkLqvETgYrIEKVFqLSKYyGwKbduYlJvPojig8k26+f0zGkaau0Xu72HJ33ef1Int10Ujgn1hiuVYh8jyCHqVwXXJUh2mWxO0aOAaoKKrRiIVIa3cxn1PB8Gm35XUIVPzADjo1RZtrPQ1QB1FOMjw33GBju6abEJJj4Y3zyvcDzB+icsOVlyg6ssUTmJFyy7FttGbSuBc8p2Er4pIqfIWDXtoisXdDPTCFnl65ClCyzyF2tY3xZE+J7YADhM2NBgX58+spy+BsKWAe4FpT/CgSb4vYRHdiWhZkueGlHCYNKF04kSt1wqOTlkW3beu27lycGFo3JEFsVljIwFQ1G79HZTGFeOSGYTPqTwvBy0Le+MPdUHNnbzudxPPowaUZ3u9198yi65RKnT58pJfJ7fth+OspAXIn1av3QdCac4d9R8xl+zdi/u7RVziYJCdwXm4XOj5Ip8Prdf+g0i9anUV6M0y/XrdxcPd4O9w/3189dVaabap9tIE5u80gGi274Nqf4j280/wFQSwMEFAACAAgA1HzvVAJumUZaEAAAuxcAABkAAABNRVRBLUlORi90aW1lc3RhbXAwMDEudHN01Zh3VBTZtoepTjSpyUEkNIKD5Opuck4CLUGyEkRSI0gUGgkjNjRNkiBBFJAoo6ggypBUJEgUEAQkSUYkiagIqCS5zbxx1HvvWu+u+2ZmrVf/1Kqz99ln1z51ft85BZK5qxF04tEG0Z+YAFpIPpn7Jkjm/gUCQDHMIBOCzjHaACBAYRAonAYMRjD87kjHAsDyPWCnQAIEABCMEggABmxJQKgBABDzfTcATgNDU9ieoCNuboRBnEII+TpX2mTP9lrbOT2ZL5E05HZa1OeGICFdaQts7yt7eJixIBYLKmDkMDicAk7JFoSFQ6Cz+WR2FEimlQPJsMV8KASAQJBHB2c/Xj3uGwNq/ZE9QA/K5v9z0gV8IO83D+Q/Wa9Rg2mCzhgGkA4BtYIh2CG6hzE4ELP3QM8orqtvgtYlBBIDXNwJAWh9QkCgj6s7wYMY4EMghqItCP5nPVwIaH1vZwOMAMi31wnKyOl6yifgd4u5ry8RjcEom5qAAtxMGCVQHiOLATHyGJwtNxNOAcThMBgMSL1s/5YcyJADe+//tRjUuYGSIcw01HZ6CBkC0Fw3KNQi2FpM+hcdhz50bD5xWtEVLqLHFyRNkC5L493R6gZKgtJJj8M5gkgQSQ+bs/UMenTiMZO0PNWbFi6vjvE82DRsWBgmg/HwRypqN+k6vWmrCmdnYveh2rXljzff2M/cJqm9fymlK0js17xDkQPyJ7quR8NEj96rdjFXjk9G1Chk0w3NaZlVCGBvPpu7xsIfkucmQXlxUciO8YADjdttpmyihzyd2dPDNCKz8TSyTyo3JGdUD6ie6ujIjXtf0MTqAWRhcsFBrZlHHDaLJjtiLzmyI1bUmcUNc+nzCASYhS3rjm2JFYL9vYpqWm9eC8RH4tdW6QjsuZrl51f0KRrF9iKAFR/B/p5rvCiSib7HY6tJTF7cODutozAivWz+9H3HcJJOrYHwbb6327p2kuk7g5zmv6zVju64q3X82uJtlscvXb9Bkc2eiKYxqhU1kJjISF6a7OddL58/IX9meOsTuq7BYJeeTsGwdkX1Ia+xYuYmnpVrTlZxKpJ4W8k8P3jCeNziYDGrFzPR0Wiy3RcdEGAXw6lxViUUMV1OamPYElzhucBZ8CDzVa0uhNOlwk4qJ40PjlKlm9HEkLg8zWNINQIvzFnqbfDulpyoyK4T6EzdSnO56SLDGE3IM0b6ZNPweQmdxPn6i3bkvHtZ7+W8C+MmlqyNpvBPDlc49gmUWz2GQAEaoJAMRIFkIAJkpn5L/OwAsAuDg1DqDRTcaxCG8YBc4Ry0PE4rJ7tvBVa1PuMQfzh3h6trRBqMSEcgqVIAh9MCACwiFoyIAo2/toCQaC13ItFPWUYmKChI+tsHKu1KkCH6BwYQXQg+RIK/jF+gs5eHi8w3BxkPH1dCsLQ70dsLlP0jHBB96Pdw/r4uAX5SVP8fgyorgoqgzJ4N9NhLHA1zBh1BBwTDN7ECwKPfEoQAXH9Cgvx7Q6FgXLB/XyHUnpl5r6YwqvJEg/sRdL+l0+ANhcNQICOC/o9H4E9QNujeqj4ly8Z8UNJsX0ZlRvFCeLsQKMIZ1xBVYPlywCaD/mlrqfxlcrJQ8Edd7kXIouDay5oXDrdDDlQtmOVYZ9Fx9O6MLodeaVBwRsOS7jrCmzd5AwZFKeJO8vZ85QPuTX3mJd0fWoh2qcuHKU8Xe8BL/VwEPT7KDKw369P9QzQ1KxZO+LT3uZvnhunsva7r0152IHqvB86rsA86j2ce4Y1DDGpvrFxI6AIetPqakIvuK6+KdZwWWZ8UmRks0K6JDkuvLCAVCwcGFas59rZEzyZbvS5Vm4ojS5k9Dwt7ONDr3lTSQzEOUwrtOJ+vsXayivK5q4mC1q/jC6344mWSfWdFlfd5wcfulY03nwSWVCJqBx7zh0rKac3i3W8taZ4XdhbwWfpwY+rItNDGJTVdrQtpuUOOljXbZ2LFkuyThj5uVyWnjJQ+uO2QMzidt+h5MDSa5eFYWa4kYn1HEucut8b22v6YY0lpSvxifM3JUZurwmitL6VeNEwCSsOH3Y+x5AbHF2YQ3aXSGut9saQXFAeBd04fTT+7NjLHnP/ZcnGDXMYH53w+sLltETfvYe3duOG3vk0Dx/MmEl5iZi+9KfMQmUJxPUxzLkgZz3UVc3HgELs8mjR6xbVSI1no/GtG96rYxelNcXqzx++2teO0nE4wqVdE40K0LiKzNJ+Z9l9JweIbuULYd7lAMnwOJEOzfgen/s30UW91Wdz/P3BiZRVl5f8FnE5/Qg781IX4Ww4c3+XgpqOFxmB/4ybwr9wE9rgJULkJADSFn0jicR7Owv3ARnXtKwJic5jCMqYZfM83r6sh672RLNAFjHfzPFi3XaNPY3WGF8nGbrcyW11lZazlLcz9mDwmR7IcHt+XVJI5WX8xHRb3HtFy0tEfxtyAy8rCka2yR0mncI84vSRCTkhno+5JHHviX3VYYN6ajsO/I0NLD8kkOUbDiLW551xtOmjNb5fVx7nBedv9WFl32TRrcFGYxLMFmWbP0LO7tKPZnjvGMtcNkYvjk5eb1rLeyuE78UcMvQsuXehO2VktLOdKyXqjYGbrm+Df4C6IJ3+ZTs14aIL3yw7q0/ahCQ89NIdrTrviw8eaLFMdKta5Od5PTM1KC9mU+coNBWpFcCDbH9xAggjqjSpB/zs6dL8jhyIo/18K/en/EXoX0Ak8+d2ulLoN/SuV3mN6daZ64fKpGmYRpJoyo4LRqG/dj0oPgf0tSs+1GwcvnRyb5bb9rGiYadBZU7qaVO3xVH1Yo2BAaZ/MiJN/ZufEjOryWU++ylOpFhYQV/o3LOpNjMWCi5Gj+esZCVHqfQlEYzrA7C5G0Z/3LmeGd18KsjfczhxVsRHThMrI9fbtgWrnCuXA6oY/KScyCbPKR6wcQJYqTUnRhNT0maEb6r1VR1aMZ5jWPmel6QgveHm5IFUuap7nLSG6mTMmHVLTcLeWYrRvQztq4rHlx9uSFRA6RBOon+WXy3Jp52ImXwGwSpc3fQmiLGTyjakTLoR02m7Ku7KoXpRR9oeQ4+ddxOPyVo0TFvTt6FTqhBrqXwp4hNZ1SvJmkTYsA7+EtWbd96Lj2YmanET1aHEkKHJiTm5OrTZq+x1AC7cNFHnYBctC+6bvLpaStsTY1mITk23dmHutbA/O8kimfHRl1FjAnyweQimtWeKqC4kKClYGlbsStXYhy56wgJ5UU9e0WazJTSdG2sK6w3OIwaInNBej4n4xkk2MFPcUHecRaYajEzr0Khat2qcflqFVwtsKneQznqyA4cGDAfUx5iDPT/MyoRvMzmEGy5/Mk+ZeTa1I9b3L6T/8uRIn4ja3P9RphqUFgnoaLmnKr7DL8thmGh45C7vKbsqQOH9EfQa5sPVO68GuJjaxRj0FMyuSigo7gJWKaI82KhvCzb1Xzs+jUJV+nnpEuvq70h/CbslcGUVj/gyl/xtU9pvQ47CgLPgXC/1eJ0sLC7SFxykfgj9aDvefHJAKl3mHsg9W9HZ+LA6VMDpJsY27/OFZ60DOemwXgH8l3JvO56Rfy8KXcOZ+bDUKcV+eE7lLLyJp2HA2uyscfyv18o2l/JwHqgpvFwOLuo8aHroCN8ino2ipTbAMsbOsri2raKlFJIW+mLsqwAYKPmvvFSo5nfHFss1bXu/Zz2WmWtIjmGu5P5lnbTB0Uz6z7esTp3ujmANNVK6o060TK9g+xc92Acg2N9+RGODW0wi+ir7/VOHxuH9IGZpJoncoNVMtZgwZmC21+V4ann/v2iLcU+dXyfgXPtwhjUZu4y6sudXHndlCPAV8jiljv3j6ScrNTXKGztGmq6i41bSLCXUiB3ny+miB1rTEoojjr/FKXi/OmKZEd5mcI/uDqauMYacdD36sv29BSxkytguvZr4rOATa8fgVBZlT/cIm5rL0hmryl5+MqQ/oWT2SdeznylG/Kz4RNGMnM2m0/tPF8FtmLsH8mbtxvNqc7lJBO6g5QiXTTcGEaZjMCtPC5vnT+/1DJJDnjB+sKrFM/Upfdf1KPJ5oNG7m31zBOh9tEKO/dlSiVMgoL4monzhl2T3vPLRYFLVhs2U9bnX+kqSQBN/QEAde6JyJdF0MZ59mm+DGLlw1drgNer0sXMNwFv380W1a5vrQJjoScdY7FrFdMiPSbJRWVuE1efyX0Dt3hWPNWkYMjSO+gk6JCjo5qoZ/BR0E/BFx/5YI/wni3P5bxNFCIH8+4rj2xjq494KMIP3X0FDkd+gzH4w+3J1pCH1zUSW4llWAYn/1y8ZfjzrqlutC86A6DVtiE+UxaK0VmDglMjn+4CKUoVd691N7zJj7aSF10sSiENckcqb8KYBoAXpiDfZTds+P8B+dGFdt9fhyneND/Kche76E4yPivjnu4n4bCUEFJVjRvkJjnXzR8E63x8ZitxZufJkK8FFfqc1vf5SFm7+1sps0V5ic2q/WP39dLc3sbW/NLEA257MsewatOZHv3Yxczexr62qz0m9KIGV0yCqVY0dgArmtwsf9yvbhjt4ojMZy6Yo+GhXeesnjRtM2I3z7JPQMR+DrY/oq/u+YAkZHnEPIxj7Z/VkFGgtCdw9hS/Cf3R4RLwSWJkrkwAKzntswvP3Z9IjnQGgqGIchw6iyBN2GAADo/Teo83c0+XFK8skA+N2U0UExTD/8JaTu7v+wwTHM3Ew//t47+s0Kw2jDNENTOK5R8loylvhsDhoCDk72DmzCFUvQuSDBgsyU8xO0vXHRn8cH3vV0Dh6JaZQW6osj2ik2PciIalLuPGRwa3IXjLj23fAQRkxEKhhxEYxIACPiYBxRBsFMOuxSDnHNiTcXRdfNdHlRa+AZkPCLy99bwv/7IoCRITQHhNfZiRHFsneKm8bem37uOTWuiOwO384IYznxVmziatw5/CJqzLfitqn/psudlxuIDOEoEt76pEohflZHo7oJqnTfHjdWvrt8ZuJOV1XBWc5GKzlp9WfqMzngh63kFndkxdX2PrOGTZpuG0/ekLis5rkLQlsG/WoxdY98U8eOLqlPpqlGvnbuCSs5Ulc7HHAl5KfO/bnkVqSXMDag4yJi19m68/XUC8vrWqkqspetCuYaBQRJWx/4DB5Cnq7D+NtfxYxcTyg+MmQqKIx16oh34XV9gduvJn+vL3Knc42wjhLkt+aqH9zE2Bm6VwWzO1sIiAYf7bhmwrfC/vjJaZjflyote8hbi0+VGVZLxzkS1of1Kws1uie8oH1zNgc+q0Qw9JU/2CnJVCQ92XabHz4HVhQMvFv+4Fv0s+s1hPRZ29NHseoTqGNP2xOKJkdDTnugBNJfRtExkVI4ZSCx/VE8L5P6nt40aBRSYtQOXR8rZDcxbLhbuWxIuXRMjwcurkKqrjwYQxpTKO9kudI25wAcu9wiT+iPrOCKfPwiTEDh3pIw163rXqvPpZNVz9QpbNzgd7qrQRoWi+zhV0p6lh5cuB0TdkPqXaLTS99H8yPKLjxvzkqG00exDQUsXGI4nPvBRluUUU9Er5FIkVxVvqZbXi/cIfOGs4XsVXVIsua5zrzU/thcXZl/AFBLAQIKAAoAAAgAAARdVVSKIflFHwAAAB8AAAAIAAAAAAAAAAAAAAAAAAAAAABtaW1ldHlwZVBLAQIUABQACAgIAARdVVQyugebjwAAAKwAAAALAAAAAAAAAAAAAAAAAEUAAAB0ZXN0LTAxLnR4dFBLAQIUABQAAgAIACN4OlQeDhsL5QAAAHABAAAVAAAAAAAAAAEAIAAAAA0BAAAwMDItdGVzdC1kb2N1bWVudC54bWxQSwECFAAUAAIACABZcFVUPBo1jpABAACQAwAAGQAAAAAAAAABACAAAAAlAgAATUVUQS1JTkYvQVNpQ01hbmlmZXN0LnhtbFBLAQIUABQAAgAIANR871QCbplGWhAAALsXAAAZAAAAAAAAAAAAIAAAAOwDAABNRVRBLUlORi90aW1lc3RhbXAwMDEudHN0UEsFBgAAAAAFAAUAQAEAAH0UAAAAAA==</dss:Base64Signature>
			</dss:SignatureObject>
		</esor:credential>
	</esor:credentialsSection>
</esor:XAIP>

=== de-bund-bsi-tr-esor/tr-esor-AIP-eIDAS-SigValidator/aip-validator-cli/src/test/resources/cases/XAIP13-asice-xades-det-single.xml
<?xml version="1.0" encoding="UTF-8"?>
<esor:XAIP xmlns:esor="http://www.bsi.bund.de/tr-esor/xaip" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:dss="urn:oasis:names:tc:dss:1.0:core:schema" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bsi.bund.de/tr-esor/xaip file:///C:/Projects/BSI/Proc-XAIPSigVal/60.Abnahme/220106-cli/211130-TR-ESOR-Schema-1.3.0/tr-esor-xaip-v1.3.xsd" XAIPVersion="1.3.0">
	<esor:packageHeader packageID="x373f4e59-69dc-4a77-9ea6-75e91a74bfc4">
		<esor:AOID>40387ca1-4497-40fa-acfa-9976132b1001</esor:AOID>
		<esor:versionManifest VersionID="V001">
			<esor:preservationInfo>
				<esor:retentionPeriod>2100-01-01+01:00</esor:retentionPeriod>
			</esor:preservationInfo>
			<esor:submissionInfo>
				<esor:clientID>remotebean_esor12</esor:clientID>
				<esor:submissionTime>2022-02-10T14:43:26.898+01:00</esor:submissionTime>
			</esor:submissionInfo>
			<esor:packageInfoUnit packageUnitID="_idx_DO-01_V001">
				<esor:protectedObjectPointer>CR-01</esor:protectedObjectPointer>
			</esor:packageInfoUnit>
		</esor:versionManifest>
		<ds:CanonicalizationMethod xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
	</esor:packageHeader>
	<esor:credentialsSection>
		<esor:credential credentialID="CR-01">
			<dss:SignatureObject>
				<!-- ASiC-E with single detached XAdES and mimetype -->
				<dss:Base64Signature>UEsDBBQACAgIABGKHksAAAAAAAAAAAAAAAAVAAAATUVUQS1JTkYvbWFuaWZlc3QueG1sjZDBCsIwEER/pexV0qonCUZvfoF+QEy3upBsQrMt6tcbBbXixdsOzMxbZr29BF+N2GeKbGBRz6FCdrElPhk47HdqBdvNOlimDrPo11GVGOe3NDD0rKPNlDXbgFmL0zEht9ENAVn0t18/QW814S9hQuvIoyrp/vrxdoP3Klk5G2gmFQFbskquCQ3YlDw5K6WyGbmtUTLV5TencHajBM3/CCm6PhL/QYpOUFSWHm14IJqf0TZ3UEsHCOVQCQO0AAAAbgEAAFBLAwQUAAgICAARih5LAAAAAAAAAAAAAAAAGgAAAE1FVEEtSU5GL3NpZ25hdHVyZXMwMDEueG1sxVjZcptaFv2VlPNIOcwCUrFvMQsxjxK8MQkQCCRm8fWN7dhJHN/u3K6u6hfVmfY5e1ysrW9/zefq05i2XdHUD3fwF+juU1rHTVLU2cOd6wj35N1fj9/Croi/HuiEt+0iq8N+aNPu0ypZd1+fth7u8r6/fAXBoS2+pH1XfGnaDIQQCibBEf6CfIE/3z1+S7qvb9LfhZPuTXSapi8T+iyIQBAEQhS4nkm6Ivt890lKHu6K5P4YwQgRJ2EUbpDjEU42CBmSKAmHEYmQ2JH88UiaSPWxeZ6yYd3URRxWxRL2q5Vq2udN8omusqYt+vz8NxrAIAw9aXCfzvF9DGP15zvwVxv++CIIezXl/ty06ee2C++7PETwzfcrrfSYtqvb02dD2/vVVPjuk3O7pA93d59cS3q469Ou/xIV9YuJXJGt83+owPrA51+efbnFC6shfZwELbUBGa1BxJEtVTCRESscQbdPwDAJhAEqPUXObYBbzcM38J3w88KbEe9MejHjwwSBKQj9/BIuo20uadsXaffd4M9zmKTd/R9H3WnDujs27bn7dfpfBhr8/cr/vdO3LYmx2BLPNd1jtGwJ+XRB1Z1TKhaWdiUBN0dQFmoXjN3/7HTw99R/S9VniefkGp9Gf+ZV3+giwk3rlsc7+cKtv8XxlFK5w4duWSq3WseB9kjV/XgIFH9hvFxz2tLdXuo2g1W90ByV2ubqcFhyUtFMZufmE4eOQSdEO0lWBgc+scKy2SX7mPHabKOblRdYJh0JrnOenVbAmnlcssOeDZQgOmjxwE8s1ycWpxwip/enbdmeG3nL2V0TkF4NFSfpIkSOThKJbzCbIQfKBapQ7eRdKneEVfVSj2MFbpeOKQ8FPQODp9rqvqyUIFfBcssfBIrQ3dFTfQ72k351/bYDBGLjYKVlAzgjt3O0p4NxW5w53oIMsa6LkLWsOgkv+BxxOJ70eI9DE25sSlZutkqv6JGw4zmjFHfmEVRr+uHhLVI/QvMcLTm9vUXugEMUF/bh24R9Ko7jCmN9+qhKErs5sSydyBk9SQydSSJbh6wcl4hKQyJrX0VbilDO5Bl2cmmVo2dxoQMm0zyGVlW+2o0RajnBfj67SFVHZ6+0zkIbOLyl0qRIwy7PZpNkCZqjHKwqRs1pm8ea6sSTzkm46rizdlKh/euaI0Gqw0Pa4mL7E92oljrxps95pslx9MUJ98kQHHaiv+8r1eInbnrekzk6511Y7RPRWxJutceWJs70d3ITSPkYa/SqP2PSXJbxBv20bzbsOmbonc+WDJBeolsWDIe4b4wzgXnHuogYi3VMW+ySwd6Ol1HhrnZd7bftAS7jG6DmywbKxvyQbrxB2POIycaIbstAMlF7wmsj8Qzy/sgJmXZ0CARPN+E23AKgCrV2yWmGYg3qVA4iQm4FQ2r4vUTsE48Y5AN01PGcskkm7edxXCrYPmN55W92GZWdCDGEs+sWQOkUFl1ZmNqAjLaO2m0nrDMQ9JCk/qluuU3auEBeB5vTCNKb2+WKDZhwQSh7WxbHYNRtqMwM/kDtpG0PeH3sZq4FZITitrqfLTcsjJsz4u9KSCjsevLnTYO2wITGtDcZ3LGDlhBY0NTIFY1XinOZkjQZ4IaDngVy8A8dS088TYdrSTD0xGVrjNYUp80tyNAmR2e8+FFu0diafyYrsDO0UIx5PdkK22BrQDBKPIgtCBbLXis33CThEzRVYAQ5iUWKp4pe4pzahEY0gRQmEmdDHS4BmqU3JIPmVNmmPIE00CXoSnO/UYKxLaUjRCE7hruRnG6W/JzXx4D2VQ/HFts4UQSy1c5n0yAC1KVw9WppxBZG9XT2hSlSQ01kRIe0ewzXDyeNSBHDCeXISHvIpQDwOFqqcb3NgX3KIRMIKlvOgFS5YJaxX2KmEQ/7ZN8pwLWfhtmWCEHT8J0kFScojeLC8pwq98ihITs8nndnexuNgEcn5syGiYwCdOjxF57H+WtMJIg9Qdqg1lv2jNtwGDPXK7Ic9EXrrK7Wo9i6cZN1vEwX6Rko3hf/3wEC+QwI1zdA4DHCrMU98X8GBHQFhEm1ukl8BQRmZ0cIBbmI1wWVdgkQvAr4YP1EujPv0MaLTo3K8pbj3mAoOGjQah8jnWiNycprXhYiNUFr0vECTesrKJD00z6byeuYpyvOPMbmYcvPmIMpXbU/V8RyvQaTd7hA835I1m9YjAzDTMsHHIevLhn0kh8YcolFrAdb8KYpd+f8mvWIe8vma9rFE+ufXYJhIOoqnuqinVFoEuKrcN4PWUznunGbdsZAOpJ6GWNXz/O55bzAh5nzVGjDSGnDvrqlJlbmngQFUggfb93ggdyG86a4U5d6pp3SrHlWD8+Sq/ucpYONmRrgDDsxKGfLoY3h1urGufCmUfOBUCZTxfOPGgLdEHmOW7zBGaY6HWUU3CCodKtsbyvhnQSw9kpfAETD0HnuYpLq7YtRTb48yuDYCFKKnhLBt7vlTGMThYU9d6v7jd8TE0aOlbhI0oqGs3EwJY42aaaZpYnnaP0pRluTZOgjuaKxuvrdfw/cynfgZmiaUxjHljJ8UeFIa/eJRKmJf9pxa5nQG3ZiUjfBT71T4Vme3chAIwaMlITFXdKUJmDcrmDZocA1eytGriSxZDbTTMoxYcQW4BeH02BccZjh05rQauq2WcQFkOTW4YTkkkYitPjDbbswQXAou0GcUFcplobr9eLWYlibj8B+ArgckJQo3NbUEs36EWvOejAdsP5GR3GwUDVXl6RQT3wyzitUECYwDrc+6HZ6FlwEVwEnl4MGFpz2+3lHAVbACrGlRrNxlc9Gr2hRH+NXo2lOAWem18FjUnyvJyvhO0yEOKQi5+hlwdMKOFOqicbhhtdyH+33G0cZDSepdbstDaMCBUNOqA2h66P58DE4gL9wB/Adq9CjNff7x2/P1PqrOaw90fG2dno/yPf3vuz5wL8h7U9dHfoFWTszJ2yztF/p+p8R9ZeX31P+Z2b6T/j+z9e8Makf9/18YDXPKc7pIwLBxD1E3qOQA+Nf4c1XFA++gb+f+1X0J+d6yOve0+LP4xdW/s97hF+a3LVJgD9oEbB8zJA4xhMo2tysDFKYnsuxnY2j2Uctwe9KvaxIXTekrZ22RVithqgcNmmyefsffAhYJrsgWVHvtOyJ2n743M96Pb5z+jsPg/8gtGnylOYvSf37iR97woqBYf/pZfLWMa05+73TfpVQ1/g/dauP4eVSPWlUNDXYxH3a33d9m4bnV+3eDr4uvH/rnR0fqwl+XAxvGx/V50tNv9bxL43EOv3ob5rHfwFQSwcIRHNfSa0JAADjEQAAUEsDBBQACAgIABGKHksAAAAAAAAAAAAAAAAIAAAAdGVzdC5iaW7zSM3JyVcozy/KSVEEAFBLBwiVGYUbDgAAAAwAAABQSwMECgAACAAAEYoeS4oh+UUfAAAAHwAAAAgAAABtaW1ldHlwZWFwcGxpY2F0aW9uL3ZuZC5ldHNpLmFzaWMtZSt6aXBQSwECFAAUAAgICAARih5L5VAJA7QAAABuAQAAFQAAAAAAAAAAAAAAAAAAAAAATUVUQS1JTkYvbWFuaWZlc3QueG1sUEsBAhQAFAAICAgAEYoeS0RzX0mtCQAA4xEAABoAAAAAAAAAAAAAAAAA9wAAAE1FVEEtSU5GL3NpZ25hdHVyZXMwMDEueG1sUEsBAhQAFAAICAgAEYoeS5UZhRsOAAAADAAAAAgAAAAAAAAAAAAAAAAA7AoAAHRlc3QuYmluUEsBAgoACgAACAAAEYoeS4oh+UUfAAAAHwAAAAgAAAAAAAAAAAAAAAAAMAsAAG1pbWV0eXBlUEsFBgAAAAAEAAQA9wAAAHULAAAAAA==</dss:Base64Signature>
			</dss:SignatureObject>
		</esor:credential>
	</esor:credentialsSection>
</esor:XAIP>
