=== de-bund-bsi-tr-esor/tr-esor-AIP-eIDAS-SigValidator/aip-validator-api/src/main/resources/wsdl/tr-esor-xaip-v1.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xaip="http://www.bsi.bund.de/tr-esor/xaip" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" xmlns:ers="urn:ietf:params:xml:ns:ers" xmlns:vr="urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#" xmlns:dss="urn:oasis:names:tc:dss:1.0:core:schema" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" targetNamespace="http://www.bsi.bund.de/tr-esor/xaip" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.3.0">
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="./deps/xmldsig-core-schema.xsd"/>
	<xs:import namespace="http://uri.etsi.org/01903/v1.3.2#" schemaLocation="./deps/XAdES01903v132-201601.xsd"/>
	<xs:import namespace="urn:ietf:params:xml:ns:ers" schemaLocation="./deps/xml-ers-rfc6283.xsd"/>
	<xs:import namespace="urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#" schemaLocation="./deps/oasis-dssx-1.0-profiles-verification-report-cs1.xsd"/>
	<xs:import namespace="urn:oasis:names:tc:dss:1.0:core:schema" schemaLocation="./deps/oasis-dss-core-schema-v1.0-os.xsd"/>
	<xs:import namespace="urn:oasis:names:tc:SAML:2.0:assertion" schemaLocation="./deps/saml-schema-assertion-2.0.xsd"/>
	<xs:import namespace="http://www.w3.org/2005/05/xmlmime" schemaLocation="./deps/xmlmime.xsd"/>
	<!--============================================================ -->
	<!-- Version 1.3.0 vom 14.03.2022 -->
	<!--============================================================ -->
	<!--============================================================ -->
	<!-- XAIP gesamt -->
	<!--============================================================ -->
	<xs:element name="XAIP" type="xaip:XAIPType"/>
	<xs:complexType name="XAIPType">
		<xs:sequence>
			<xs:element name="packageHeader" type="xaip:packageHeaderType"/>
			<xs:element name="metaDataSection" type="xaip:metaDataSectionType" minOccurs="0"/>
			<xs:element name="dataObjectsSection" type="xaip:dataObjectsSectionType" minOccurs="0"/>
			<xs:element name="credentialsSection" type="xaip:credentialsSectionType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="XAIPVersion" use="required" fixed="1.3.0"/>
	</xs:complexType>
	<!--============================================================ -->
	<!-- packageHeaderType -->
	<!--============================================================ -->
	<xs:complexType name="packageHeaderType">
		<xs:sequence>
			<xs:element name="AOID" type="xs:string" minOccurs="0"/>
			<xs:element name="packageInfo" type="xs:string" minOccurs="0"/>
			<xs:element name="versionManifest" type="xaip:versionManifestType" maxOccurs="unbounded"/>
			<xs:element ref="ds:CanonicalizationMethod" minOccurs="0"/>
			<xs:element name="extension" type="xaip:extensionType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="packageID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="extensionType">
		<xs:sequence>
			<xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="versionManifestType">
		<xs:sequence>
			<xs:element name="versionInfo" type="xs:string" minOccurs="0"/>
			<xs:element name="preservationInfo" type="xaip:preservationInfoType"/>
			<xs:element name="submissionInfo" type="xaip:submissionInfoType" minOccurs="0"/>
			<xs:element name="packageInfoUnit" type="xaip:packageInfoUnitType" maxOccurs="unbounded"/>
			<xs:element ref="xaip:idAssignmentList" minOccurs="0"/>
			<xs:element name="extension" type="xaip:extensionType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="VersionID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="preservationInfoType">
		<xs:sequence>
			<xs:element name="retentionPeriod" type="xs:date"/>
			<xs:element name="status" type="xs:string" minOccurs="0"/>
			<xs:element name="extension" type="xaip:extensionType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="submissionInfoType">
		<xs:sequence>
			<xs:element name="clientID" type="saml:NameIDType"/>
			<xs:element name="submissionUnit" type="saml:NameIDType" minOccurs="0"/>
			<xs:element name="submissionAuthor" type="saml:NameIDType" minOccurs="0"/>
			<xs:element name="submissionTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="extension" type="xaip:extensionType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="packageInfoUnitType">
		<xs:sequence>
			<xs:element name="unitType" type="xs:string" minOccurs="0"/>
			<xs:element name="textInfo" type="xs:string" minOccurs="0"/>
			<xs:element name="protectedObjectPointer" type="xs:IDREF" maxOccurs="unbounded"/>
			<xs:element name="unprotectedObjectPointer" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="packageInfoUnit" type="xaip:packageInfoUnitType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="extension" type="xaip:extensionType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="packageUnitID" type="xs:ID" use="required"/>
	</xs:complexType>
	<!--============================================================ -->
	<!-- MetadataSection -->
	<!--============================================================ -->
	<xs:complexType name="metaDataSectionType">
		<xs:sequence>
			<xs:element ref="xaip:metaDataObject" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="metaDataObject" type="xaip:metaDataObjectType"/>
	<xs:complexType name="metaDataObjectType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="xaip:binaryMetaData"/>
				<xs:element name="xmlMetaData" type="dss:AnyType"/>
			</xs:choice>
			<xs:element ref="xaip:checkSum" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="metaDataID" type="xs:ID" use="required"/>
		<xs:attribute name="relatedObjects" type="xs:IDREFS" use="required"/>
		<xs:attribute name="category" type="xs:string"/>
		<xs:attribute name="classification" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
	<xs:element name="binaryMetaData" type="xaip:binaryMetaDataType"/>
	<xs:complexType name="binaryMetaDataType" xmime:expectedContentTypes="*/*">
		<xs:simpleContent>
			<xs:extension base="xs:base64Binary">
				<xs:attribute name="MimeType" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!--============================================================ -->
	<!-- DataObjectsSection -->
	<!--============================================================ -->
	<xs:complexType name="dataObjectsSectionType">
		<xs:sequence>
			<xs:element ref="xaip:dataObject" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="binaryData" type="xaip:binaryDataType"/>
	<xs:complexType name="binaryDataType" xmime:expectedContentTypes="*/*">
		<xs:simpleContent>
			<xs:extension base="xs:base64Binary">
				<xs:attribute name="MimeType" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="dataObject" type="xaip:dataObjectType"/>
	<xs:complexType name="dataObjectType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="xaip:binaryData"/>
				<xs:element name="xmlData" type="dss:AnyType"/>
			</xs:choice>
			<xs:element ref="xaip:checkSum" minOccurs="0"/>
			<xs:element name="transformInfo" type="xaip:tranformInfoType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="dataObjectID" type="xs:ID" use="required"/>
		<xs:attribute name="relatedObjects" type="xs:IDREFS"/>
	</xs:complexType>
	<xs:element name="checkSum" type="xaip:checkSumType"/>
	<xs:complexType name="checkSumType">
		<xs:sequence>
			<xs:element name="checkSumAlgorithm" type="xs:anyURI"/>
			<xs:element name="checkSum" type="xs:hexBinary"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="tranformInfoType">
		<xs:sequence>
			<xs:element name="transformObject" type="xaip:transformObjectType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="transformObjectType">
		<xs:sequence>
			<xs:element name="transformAlgorithm" type="xs:anyURI"/>
			<xs:element name="Parameters" type="xs:anyType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="transformObjectID" type="xs:ID" use="required"/>
		<xs:attribute name="order" type="xs:string"/>
	</xs:complexType>
	<!--============================================================ -->
	<!-- CredentialsSection -->
	<!--============================================================ -->
	<xs:complexType name="credentialsSectionType">
		<xs:sequence>
			<xs:element ref="xaip:credential" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="credential" type="xaip:credentialType"/>
	<xs:complexType name="credentialType">
		<xs:choice>
			<xs:element ref="dss:SignatureObject"/>
			<xs:element name="certificateValues" type="xades:CertificateValuesType"/>
			<xs:element name="revocationValues" type="xades:RevocationValuesType"/>
			<xs:element ref="xaip:evidenceRecord"/>
			<xs:element ref="vr:VerificationReport"/>
			<xs:element name="other" type="xaip:extensionType"/>
		</xs:choice>
		<xs:attribute name="relatedObjects" type="xs:IDREFS"/>
		<xs:attribute name="credentialID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:element name="evidenceRecord" type="xaip:EvidenceRecordType"/>
	<xs:complexType name="EvidenceRecordType">
		<xs:choice>
			<xs:element name="xmlEvidenceRecord" type="ers:EvidenceRecordType"/>
			<xs:element name="asn1EvidenceRecord" type="xs:base64Binary"/>
		</xs:choice>
		<xs:attribute name="AOID" type="xs:string"/>
		<xs:attribute name="VersionID" type="xs:string"/>
	</xs:complexType>
	<!--============================================================ -->
	<!-- Delta-XAIP -->
	<!--============================================================ -->
	<xs:element name="DXAIP" type="xaip:DXAIPType"/>
	<xs:complexType name="DXAIPType">
		<xs:complexContent>
			<xs:extension base="xaip:XAIPType">
				<xs:sequence>
					<xs:element name="updateSection" type="xaip:updateSectionType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="updateSectionType">
		<xs:sequence>
			<xs:element name="prevVersion" type="xs:string"/>
			<xs:element name="placeHolder" type="xaip:placeHolderType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="placeHolderType">
		<xs:attribute name="objectID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:element name="idAssignmentList" type="xaip:idAssignmentListType"/>
	<xs:complexType name="idAssignmentListType">
		<xs:sequence>
			<xs:element ref="xaip:idAssignmentPointer" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="idAssignmentListID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:element name="idAssignmentPointer" type="xaip:idAssignmentPointerType"/>
	<xs:complexType name="idAssignmentPointerType">
		<xs:sequence>
			<xs:element ref="xaip:checkSum"/>
		</xs:sequence>
		<xs:attribute name="objectRef" type="xs:IDREF" use="required"/>
	</xs:complexType>
</xs:schema>

=== de-bund-bsi-tr-esor/tr-esor-AIP-eIDAS-SigValidator/aip-validator-soap/src/test/resources/samples/XAIP13-cades-det-single.xml
<?xml version="1.0" encoding="UTF-8"?>
<esor:XAIP xmlns:esor="http://www.bsi.bund.de/tr-esor/xaip" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:dss="urn:oasis:names:tc:dss:1.0:core:schema" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bsi.bund.de/tr-esor/xaip file:///C:/Projects/BSI/Proc-XAIPSigVal/60.Abnahme/220106-cli/211130-TR-ESOR-Schema-1.3.0/tr-esor-xaip-v1.3.xsd" XAIPVersion="1.3.0">
	<esor:packageHeader packageID="x373f4e59-69dc-4a77-9ea6-75e91a74bfc4">
		<esor:AOID>40387ca1-4497-40fa-acfa-9976132b1001</esor:AOID>
		<esor:versionManifest VersionID="V001">
			<esor:preservationInfo>
				<esor:retentionPeriod>2100-01-01+01:00</esor:retentionPeriod>
			</esor:preservationInfo>
			<esor:submissionInfo>
				<esor:clientID>remotebean_esor12</esor:clientID>
				<esor:submissionTime>2017-02-10T14:43:26.898+01:00</esor:submissionTime>
			</esor:submissionInfo>
			<esor:packageInfoUnit packageUnitID="_idx_DO-01_V001">
				<esor:protectedObjectPointer>DO-01</esor:protectedObjectPointer>
				<esor:unprotectedObjectPointer>CR-01</esor:unprotectedObjectPointer>
			</esor:packageInfoUnit>
		</esor:versionManifest>
		<ds:CanonicalizationMethod xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
	</esor:packageHeader>
	<esor:dataObjectsSection>
		<esor:dataObject dataObjectID="DO-01">
			<esor:binaryData>DQpCdW5kZXNhbXQgZvxyIFNpY2hlcmhlaXQgaW4gZGVyIEluZm9ybWF0aW9uc3RlY2huaWsgKEJTSSkNCg0KVGVzdGRva3VtZW50Lg0KDQoyMDE5</esor:binaryData>
		</esor:dataObject>
	</esor:dataObjectsSection>
	<esor:credentialsSection>
		<esor:credential credentialID="CR-01" relatedObjects="DO-01">
			<dss:SignatureObject>
				<dss:Base64Signature>MIAGCSqGSIb3DQEHAqCAMIACAQExDzANBglghkgBZQMEAgEFADCABgkqhkiG9w0BBwEAAKCAMIIIbDCCBiSgAwIBAgIQFlis0jU1NisR2UdUuXFHkDA9BgkqhkiG9w0BAQowMKANMAsGCWCGSAFlAwQCA6EaMBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgOiAwIBQDBbMQswCQYDVQQGEwJERTEVMBMGA1UEChMMRC1UcnVzdCBHbWJIMRwwGgYDVQQDExNELVRSVVNUIENBIDMtMSAyMDE2MRcwFQYDVQRhEw5OVFJERS1IUkI3NDM0NjAeFw0xODAxMDkwNTQyMTFaFw0yMTAxMTkwNTQyMTFaMFsxCzAJBgNVBAYTAkRFMS0wKwYDVQQDDCRJbnRlcm9wZXJhYmlsaXTDpHRzdGVzdGVyIFRSLUVTT1I6UE4xHTAbBgNVBAUTFERUUldNNzMwMjg3MTE1NTUyMzIyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAujqTuHyYdclpnhNj1viAc7xfZKNfYgci7b474u6cxF9SNtAps1ROVkfO9epgexeiHuOyd4E9A3DP5G/PTrZXmB2u2ybfek4lotZ9TbDa/oi4tdeHiekGTFVPBAmgqBqnFoHR11rAZu1Lx3SfSvRvRpyXqezbTo7EK+2ZOuGJvydUOgFwyymflfEx7NyoRUjcrOR4utLFZAHd2ipuRwNQkFco2P21NMomd8/5/CNZeHoFH1+BMLCal1ICVWfx43hfiXfL2M8jEBoo3wLn1OvcHl9jv4tRCBkQ92Kp/ysq2jqeeJNqZSrQiK3E3f46YIX+J1IqA1ZFlOc2NHe0vAsEYQIDAQABo4IDyjCCA8YwHwYDVR0jBBgwFoAU++3frUvwJbXSet2fmh0vbQlQIccwgeQGCCsGAQUFBwEDBIHXMIHUMBUGBgQAjkYBAjALEwNFVVICAQACAQAwCAYGBACORgEBMAgGBgQAjkYBBDCBkQYGBACORgEFMIGGMEEWO2h0dHA6Ly93d3cuZC10cnVzdC5uZXQvaW50ZXJuZXQvZmlsZXMvRC1UUlVTVF9QS0lfRFNfREUucGRmEwJERTBBFjtodHRwOi8vd3d3LmQtdHJ1c3QubmV0L2ludGVybmV0L2ZpbGVzL0QtVFJVU1RfUEtJX0RTX0VOLnBkZhMCRU4wEwYGBACORgEGMAkGBwQAjkYBBgEwgfoGCCsGAQUFBwEBBIHtMIHqMDMGCCsGAQUFBzABhidodHRwOi8vZHRyLWNhLTMtMS0yMDE2Lm9jc3AuZC10cnVzdC5uZXQwQgYIKwYBBQUHMAKGNmh0dHA6Ly93d3cuZC10cnVzdC5uZXQvY2dpLWJpbi9ELVRSVVNUX0NBXzMtMV8yMDE2LmNydDBvBggrBgEFBQcwAoZjbGRhcDovL2RpcmVjdG9yeS5kLXRydXN0Lm5ldC9DTj1ELVRSVVNUJTIwQ0ElMjAzLTElMjAyMDE2LE89RC1UcnVzdCUyMEdtYkgsQz1ERT9jQUNlcnRpZmljYXRlP2Jhc2U/MHEGA1UdIARqMGgwCQYHBACL7EABAjBbBgsrBgEEAaU0AoEWATBMMEoGCCsGAQUFBwIBFj5odHRwOi8vd3d3LmQtdHJ1c3QubmV0L2ludGVybmV0L2ZpbGVzL0QtVFJVU1RfUm9vdF9QS0lfQ1BTLnBkZjCB8AYDVR0fBIHoMIHlMIHioIHfoIHchmlsZGFwOi8vZGlyZWN0b3J5LmQtdHJ1c3QubmV0L0NOPUQtVFJVU1QlMjBDQSUyMDMtMSUyMDIwMTYsTz1ELVRydXN0JTIwR21iSCxDPURFP2NlcnRpZmljYXRlcmV2b2NhdGlvbmxpc3SGMmh0dHA6Ly9jcmwuZC10cnVzdC5uZXQvY3JsL2QtdHJ1c3RfY2FfMy0xXzIwMTYuY3JshjtodHRwOi8vY2RuLmQtdHJ1c3QtY2xvdWRjcmwubmV0L2NybC9kLXRydXN0X2NhXzMtMV8yMDE2LmNybDAdBgNVHQ4EFgQUz3ctW1D1HxL6hDzDpFu7Bk7XCrkwDgYDVR0PAQH/BAQDAgZAMCoGBSskCAMIBCEMH0ludGVyb3BlcmFiaWxpdMOkdHN0ZXN0IFRSLUVTT1IwPQYJKoZIhvcNAQEKMDCgDTALBglghkgBZQMEAgOhGjAYBgkqhkiG9w0BAQgwCwYJYIZIAWUDBAIDogMCAUADggIBAE/9cfGQ7jMMEak/+9c3pbIolCulqVArO5fqmIR+7NlxT1cK6XpmNuFO9sZgd9TjUoFYmoyzolUPqc8ydrUQ/FC0sBVrRmo3Lbtx2grc8DKyoo06lqkAKI3rYsZ6nOaLh4OA2ilNLWNscxais9RRjvgXZfemsqT4L2GKz6W2DfmkgG757HnWvKuzvWI+LKPawglbFSOB8P6GrF/XyVtLSTWx+ka+Bdb1QsWJOD1Z0vHFiW4eclfry4uAic8QbeDfh3X65eSiymv2LQBbNk4TxTKhDmtOlLYqovfkFYirku3rWkNsD1pjm/sjKUmtTetePo53+dVAbfkhpdBQ4LtHvodBo5IH5AI3GfY0DLDrF80Xs5xj6YpU4P8yKe6SFfM1eDapTU/cXgea17vkuEoT+YVJcSj+sUYedqEPJJXnyPFpB3L4KhhDqoEz9NPswjx1vZ06TIjichjXq0UrD7h5829ZgzLmFRE6QKefObNLnmfFPr4UpwllrBk01u/1Zxwu62LSzTh0FEMDLwh5fJbALqCIHhsGiXija29zPZqIqsXzMdeOfxk4Rl3ViRQZjFWQvBv+fT/DS5+R5eOTu7BlUBontab+FOR53FkogNLNnmAY/cqdChr5diQqqMt+GSmKQEKKiJbJEHZTkW8rLpZhXvpMt/53z+Bd0NvDJ07lzF0JAAAxggLZMIIC1QIBATBvMFsxCzAJBgNVBAYTAkRFMRUwEwYDVQQKEwxELVRydXN0IEdtYkgxHDAaBgNVBAMTE0QtVFJVU1QgQ0EgMy0xIDIwMTYxFzAVBgNVBGETDk5UUkRFLUhSQjc0MzQ2AhAWWKzSNTU2KxHZR1S5cUeQMA0GCWCGSAFlAwQCAQUAoIIBBTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xOTEwMjUxMTQ1MTJaMC8GCSqGSIb3DQEJBDEiBCDDL+1tn2qcwXxKCYpy8wkoKDJVkk/aT8ZNiNyWTl98KTA3BgsqhkiG9w0BCRACLzEoMCYwJDAiBCAoidkQhGwSlfYDfbZidiw7MfHeFUlff/MPvl+g2YXwZTBhBgkqhkiG9w0BCTQxVDBSMA0GCWCGSAFlAwQCAQUAoUEGCSqGSIb3DQEBCjA0oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIDBBBgkqhkiG9w0BAQowNKAPMA0GCWCGSAFlAwQCAQUAoRwwGgYJKoZIhvcNAQEIMA0GCWCGSAFlAwQCAQUAogMCASAEggEApapPUQkXkkVFJ6xfJaOKJmOYw7VLAmIgKNOe4YUwOyLeOQcsmuVK/F7n/4v68c/UKK1w6M0CGHtPKXDe1ByA7ofBZa+CZw8rrbanioX2n9soKAFZrlYALdqbpyxFwmhdPWQFUzkHCW38cpUALokM4A5XlKqHrkYJVkWvZROp1fjHI2rFYXuFwV1/lw4OzM8uOcz1lJYl351ww7X/Z/V0lMuG7sVoo1byuBYh3D6ETchJw5Zf0temMFkX464pDR6n2ew/4ybmajowYG54TOorEBdgiYbEMQA72H3PuB47s3/G+9AgqnSorqvsF7BMC/1+3fTxASfn8Zjkdi7KuXFncKEAAAAAAAAA</dss:Base64Signature>
			</dss:SignatureObject>
		</esor:credential>
	</esor:credentialsSection>
</esor:XAIP>

=== de-bund-bsi-tr-esor/tr-esor-AIP-eIDAS-SigValidator/aip-validator-cli/src/test/resources/AIP/C-24.xml
<?xml version="1.0" encoding="UTF-8"?>
<esor:XAIP xmlns:esor="http://www.bsi.bund.de/tr-esor/xaip" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:dss="urn:oasis:names:tc:dss:1.0:core:schema" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bsi.bund.de/tr-esor/xaip file:///C:/Projects/BSI/Proc-XAIPSigVal/60.Abnahme/220106-cli/211130-TR-ESOR-Schema-1.3.0/tr-esor-xaip-v1.3.xsd" XAIPVersion="1.3.0">
	<esor:packageHeader packageID="x373f4e59-69dc-4a77-9ea6-75e91a74bfc4">
		<esor:AOID>40387ca1-4497-40fa-acfa-9976132b1001</esor:AOID>
		<esor:versionManifest VersionID="V001">
			<esor:preservationInfo>
				<esor:retentionPeriod>2100-01-01+01:00</esor:retentionPeriod>
			</esor:preservationInfo>
			<esor:submissionInfo>
				<esor:clientID>remotebean_esor12</esor:clientID>
				<esor:submissionTime>2022-02-10T14:43:26.898+01:00</esor:submissionTime>
			</esor:submissionInfo>
			<esor:packageInfoUnit packageUnitID="_idx_DO-01_V001">
				<esor:protectedObjectPointer>CR-01</esor:protectedObjectPointer>
			</esor:packageInfoUnit>
		</esor:versionManifest>
		<ds:CanonicalizationMethod xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
	</esor:packageHeader>
	<esor:credentialsSection>
		<esor:credential credentialID="CR-01">
			<dss:SignatureObject>
				<!-- ASiC-E with single detached TSP_NOK and mimetype -->
				<dss:Base64Signature>UEsDBAoAAAgAAARdVVSKIflFHwAAAB8AAAAIAAAAbWltZXR5cGVhcHBsaWNhdGlvbi92bmQuZXRzaS5hc2ljLWUremlwUEsDBBQACAgIAARdVVQyugebjwAAAKwAAAALAAAAdGVzdC0wMS50eHQtjTEOgkAQRXsS7jAlFBpcY2MJNrTiBTYw7E6Q2c3sEMLdLURi+/Lff3lWLzxgsrPC+BHoqPcoHkmBGAYUaHkMMlulwEmx90wTFHXXlnmWZ6/nqbpezO0ONa5IaUXRXbdvXdjBJFvU4MRGT6n3kMgxHQt4hGmZkRWPF0w6/MH5B5oQNyHnFfYQFE0JpjLmC1BLBwgyugebjwAAAKwAAABQSwMEFAACAAgAI3g6VB4OGwvlAAAAcAEAABUAAAAwMDItdGVzdC1kb2N1bWVudC54bWx9kEFLw0AQhc8K/odhT3rINlkRJCQptEEQ9GJT8Jpmx3QwncjsRvS/efOPuTFozcXrm/e9x7xs+Xbo4BXFUc+5SnSsALnpLXGbq211E12rZXF2mrFL0gqdL2uPDAFilwYtV4NQunOkdwNbbVF7iS8Tc6V9MKtAnkwoeeyK6iH6PsKYZPvn4YDss8XR8GNfoWv2ghRC26KsHZDzgMQzEJ4+PwQsIZS1uIB3wQ0WBR7v76INtVz7QZD11DDLnIpMuu5f3oXavf99yfz/km5EFUfqfH0Bq80tmNjEY82fxHG1xWy2oHwBUEsDBBQAAgAIAFlwVVQ8GjWOkAEAAJADAAAZAAAATUVUQS1JTkYvQVNpQ01hbmlmZXN0LnhtbNWTXW/aMBSG/0pkLqvETgYrIEKVFqLSKYyGwKbduYlJvPojig8k26+f0zGkaau0Xu72HJ33ef1Int10Ujgn1hiuVYh8jyCHqVwXXJUh2mWxO0aOAaoKKrRiIVIa3cxn1PB8Gm35XUIVPzADjo1RZtrPQ1QB1FOMjw33GBju6abEJJj4Y3zyvcDzB+icsOVlyg6ssUTmJFyy7FttGbSuBc8p2Er4pIqfIWDXtoisXdDPTCFnl65ClCyzyF2tY3xZE+J7YADhM2NBgX58+spy+BsKWAe4FpT/CgSb4vYRHdiWhZkueGlHCYNKF04kSt1wqOTlkW3beu27lycGFo3JEFsVljIwFQ1G79HZTGFeOSGYTPqTwvBy0Le+MPdUHNnbzudxPPowaUZ3u9198yi65RKnT58pJfJ7fth+OspAXIn1av3QdCac4d9R8xl+zdi/u7RVziYJCdwXm4XOj5Ip8Prdf+g0i9anUV6M0y/XrdxcPd4O9w/3189dVaabap9tIE5u80gGi274Nqf4j280/wFQSwMEFAACAAgACXwCVYTgVH1aEAAAuxcAABkAAABNRVRBLUlORi90aW1lc3RhbXAwMDEudHN01Zh3VBTZtoepTjSpyUEkNIKD5OpucpQg0JKjEkRSI0gUGgkjNrRNkiBBFJAog6ggypBUJEgUEAQkSUYkiagIqCS5zbxx1HvvWu+u+2ZmrVf/1Kqz99ln1z51ft85BZK5qxF04lH6UZ+YAFpIHpn7Jkjm/gUCQDHMIBOCzjFKHyBAYRAonAYMRjD87kjHAsDyPGCnQAIEABCMEggABmxJQKgBABDzfTcATgNDR7I9QUfc3AiDOIUQ8rSvtsme7bW2c3oyXyJpwO20qMcNQUK6UhfY3lf28DBjQSwWVMDIYXA4BZySLQgLh0Bn88jsKJBMKweSYYt5UAgAgSBNBmc/XjvuGw1q/pE9QA/K5v1z0vl8IO83D+Q/Wa9Tgx0GnTEMIB0CagVDsEN0jmBwIGbvgZ5RXEfPGK1DCCQGuLgTAtB6hIBAH1d3ggcxwIdADEVbEPzPergQ0HrezvoYAZBvrxOUkdP1lE/A7xZzX18iGoNRNjUGBbiZMEqgPEYWA2LkMThbbiacAojDYTAYkHrZ/i05kCEH9t7/azGocwMlQ5hpqO30EDIEoCnUL9Ak2FpM+hcdhz50bD5xWtEVLqLLFyRNkC5L5d3R7AZKgtJIj8M5gkgQSQ+bs/UMunTi0ZO0PNWbFi6vjvE82DRoWBgmg3HwRypqN+k6vWmrCmZnYvah2rXkjzff2M/cJqm1fym5K0js19xDFwbkT3QVRsFETe5Vu5grxyUhahSy6IbmNM0qBLA3n81dZ+EPyXWToLy4JGTHeMCBxu02UxbRQ57O7OkRGpHZOBrZJ5UbkjOqB1RPdXTkxL7Pb2L1ADIxOeCg5swjDptF4x2xlxxZESvqzOIGOfS5BALMwpZ1x7bECsH+XkU1tTe3BeIj8WurdAT2XM3y86t6FI1iexHAio9gf881ThTJRN/jsdUkJi9ulJXaURCRVjZ/+r5jOEm7Vl/4Nt/bbR07ybSdQU7zX9ZqR3fc1Tp+bfE2y+WXrt+gyGZNRNEY1orqS0ykJy1N9vOul8+fkD8zvPUJXdegv0tPp2BQu6L6kNdIMWMTz8o1J6s4dYF4W8k8L3jCaNziYDGrFzPR0XCy3RcdEGAXzalxViUUMV1OamPYElzhuciZ/yDjVa0OhNOlwk4qO5UPjlKlmzmMIXF5mkeTagRemLPU2+DdLTlRF7pOoDN0Ks3lposMog9DnjHSJ5mGz0toJ8zXX7Ij597LfC/nXRA7sWRtOIV/cqTCsU+g3OoxBArQAAVkIBIkAxEgM/Vb4mcHgF0YHIRSb6DgXoMwjAfkCueg5XFaOdl9K7Cq9RmH+MO5O1xdI9JgRBoCSZUCOJwWAGARMWBEJGj0tQWERGm6E4l+yjIyQUFB0t8+UGlXggzRPzCA6ELwIRL8ZfwCnb08XGS+Och4+LgSgqXdid5eoOwf4YCoQ7+H8/d1CfCTovr/GFRZEVQEZfZsoMde4miYM+gIOiAYvokVAJp8SxACcP0JCfLvDYWCccH+fYVQe2bmvZrCqMoTBe5H0P2WToM3FA5DgYwI+j8egT9B2aB7q/qULBvzQUmzfemV6cUL4e1CoAhnbENkvuXLAZt0+qetpfJXyElCwR91uBchi4JrL2teONwOOVC1YJZtnUnH0bszuhx6tUHBGQ1LvOsIb97kDRgUpYg7ydvzlQ+4N/WZl3R/aCHapSwfoTxd7AEv93MRdPkoM7DezE/3D9HUrFg44VPf52yeG6az9yrUo73iQPReD5xXYR90Hs84yhuLGNTaWLkY3wU8aPU1JhfdV14V6zgtsj4pMjOYr1UTFZZWmU8qFg4MKlZz7G2Jmk2yel2qNhVLljJ7Hhb2cKDXvamkh2IUphTacT5PY+1kFeVzVxMFrVfHF1rxxcs4686KKu/z/I/dKxtvPgksqUTUDjzmD5WU05zFu99aOnxe2FnAZ+nDjamj00Ibl9V0NC+m5gw5WtZsn4kRS7RPHPq4XZWUPFL64LZD9uB07qLnwdAolodjZTmSiPUdSZy73Brba/tjjiWlyXGLcTUnR22uCaM1v5R60TAJKA0fcT/GkhMcV5BOdJdKbaz3xZJeUBwE3jl9NP3s2sgcff5ny8UNchkfnPP5wOa2Rey8h7V344bf+jYNHM+bQHiJmb38psxDZArF9TDVOT95PMdVzMWBQ+zKaOLoVddKjSSh868Z3atiFqc3xenNHr/b1orVdDrBpF4RhQvRvITMPPzMtP9qMhbfyBXCvssFkuFzIBma+Ts49W6mjXqry+L+/4ETK6soK/8v4HT6E3Lgpy7E33Lg+C4HN21NNAb7GzeBf+UmsMdNgMpNAKAp+EQSj/VwFu4HNqprXxEQm8MUlrHDwfd8c7saMt8bygJdwHg3z4N12zX6VFZneJFszHYrs9U1VsZa3oKcj0ljciTL4fF9iSUZk/WX0mCx7xEtJx39YcwNuMxMHNkqa5R0CveI00si5IR0FuqexLEn/lVHBOat6Tj8O9I1dZFMkmM0jFibe87VpoPW/HaZfZwbnLfdj5V1l02zBheFSTxbkGn2DD27Szua5bljJFNogFwcn7zStJb5Vg7fiT9q4J1/+WJ38s5qQTlXcuYbBTNb33j/BndBPPnLdEr6Q2O8X1ZQn5YPTXjooTlcc+pVHz7WJJnqULHOzfF+YkpmasimzFduKFArggPZ/uAGEkRQb1QJ+t/RofMdORRB+f9S6E//j9C7gE7gye92pdRt6F+p9B7TqzPVC1dO1TCLINWUGRUMR33rflR6COxvUXqu3Vh46eTYLLftZ0WDDP3OmtLVxGqPp+rDGvkDSvtkRpz8MzonZlSXz3ryVZ5KsbCAuNK/YVFvYiwWXLwwmreeHh+p3hdPNKIDzO5iFP1573Kme/clI3vD7cxRFRvRTaj0HG/fHqhWjlA2rG74k3ICkzCrfMTKAWSp0pQUTUhNnxm6od5bdWTFaIZp7XNmqrbwgpeXC1Ll0uHzvCVEN3PGxENqGu7WUoz2bWjHw3hs+fG2JAWENtEY6mf55Ypc6rnoyVcArNLlTV+8KAuZfGPqhAshjbab8q4sshdlmPUh5Ph5F/HY3FWj+AU9OzqVOqGG+pcCHqF1nZK8maQNy8AvYa2Z973oeHYiJydRPZoc8YqcmJObU6uNWn4H0MJtA0UedsGy0L7pu4ulpC0xtrWYhCRbN+ZeK9uDszySyR9dGTUW8CeLh1BKa5a46gKigoKVfuWuRK1dyLInLKAnxdQ1dRZrfNOJkbag7sgcYrDoCc2lyNhfDGUTLoh7io7ziDTD0fEduhWLVu3TD8vQKuFtBU7y6U9WwPDgwYD6aHOQ56d5mdANZucw/eVP5olzr6ZWpPreZfcf+VyJE3Gb2x/qNMPSAkE9DZc05VfYZXlsMw2/MAu7xm7KkDB/VH0GubD1TvPB7mFsQo16MmZWJAUVdgArFdEeZVg2hJt7r5yXS6Eq/Tz1iHTtd6U/hN2SuTqKxvwZSv83qOw3ocdhQVnwLxb6vU6WFhZoC49TPgR/tBzuPzkgFSzzDmUdrOjt/FgcKmF4kmIbe+XDs9aB7PWYLgD/Srg3jc9Jr5aFL/7M/ZhqFOK+PCdyl15E0qDhbFZXOP5WypUbS3nZD1QV3i4GFnWbGBy6CtfPo6Noqk2wDLGzrK4tq2iqRSSGvpi7JsAGCj5r7xUqOZ3+xbLNW1732c9lpprSI5jrOT+ZZ24wdFM+s+3rE6d7o5gNTVCuqNOpE8vfPsXPdhHIMjffkRjg1tUIvoa+/1Th8bh/SBmaSaJ3KCVDLXoMGZgltfleGp537/oi3FP7V8m4Fz7cIY2GbuMurDnVx53ZQjwFfI4pY794+knKzU1yhs7RpqmouNW0iwl1Igd5cvtogdbUhKKI46/xSl4vzpgmR3UZnyP7gymrjGGnHQ9+rL9vQUsZMrILr2a+KzgE2vH4FQWZU/3CJuYydYdq8pafjKkP6Fo9knXs58pWvys+ETRjJzNpuP7TpfBbZi7B/Bm7sbxanO5SQTuoOUIl003B+GmYzArTwub50/v9QySQ54werCqxTP1KX1V4NQ5PNBw382+uYJ2P0o/WWzORKBUyzE0k6iVMWXbPOw8tFkVu2GxZj1udvywpJME3NMSBFzpnLF0Xzdl3uE1wYxeuGjPcBi0sC9cwmEU/f3Sblrk+tImORJz1jkFsl8yINBumllV4TR7/JfTOXeEYs5YRA6OIr6BTooJOjqrhX0EHAX9E3L8lwn+COLf/FnG0EMifjziuvbEO7r0gI0j/NTQU+R36zAejjnRnGEDfXFIJrmUVoNhf+7Lx16OOuuW62DyoTsOW0ER5DFprBiZMiUyOP7gEZeiV3v3UHj3mflpInTSxKMQ1iZwpfwogWoCeGP39lN3zI/wmE+OqrR5fCjk+xH0asueLPz4i7pvtLu63ER+UX4IV7Ssw0s4TDe90e2wkdmvhxpepAB/1ldq89keZuPlbK7uJcwVJKf1q/fOFaqlmb3trZgGyOZ9l2TNozYk872bkakZfW1eblV5TPCm9Q1apHDsCE8hpFT7uV7YPZ3KjIArLpSP6aFR46yWPG03bjPDtk9AzHIGvj+mp+L9jChgdcQ4hG/lk9WfmaywI3T2ELcF/dntEvBhYmiCRDQvMfG7D8PZn06OeA6EpYCyGDKPKEnQbAgCg99+gzt/R5McpySMD4HdTRgfFMP3wl5C6u//DBscwczP9+HvP5JsVhtGCHQ5N5rhOyW1JX+KzOWgAODjZO7AJVyxB54IE8zOSz0/Q9sZGfR4feNfTOXg0ulFaqC+WaKfY9CA9skm585D+rcldMOL6d8NDGDERKWDEJTAiHoyIhXFE6gczabNLOcQ2J9xcFF030+FFrYFnQMIvLn9vCf/viwBGhtAcEF5nJ0YUy94pbhp7b/q559S4IrI7fDs9jOXEW7GJa7Hn8IuoMd+K26b+my53Xm4g0oUjSXjrkyoF+FltjeomqNJ9e9xY+e7ymYk7XVX5ZzkbreSk1Z+pz2SDH7aSWtyRFdfa+8waNmm6bTx5Q2Izm+cuCm3p96tF1z3yTRkzWVKfTFW98Nq5J6zkaF3tcMDVkJ869+eQW5FewtiAjkuIXWfrztdTLywLNVNUZK9Y5c81CgiStj7w6T+EPF2H8be/ih4pjC8+OmQqKIx16ohz4XV9gduvJn+v78JO5xphHSXIb81VP7iJsTNwrwpmd7YQEA026bhuzLfC/vjJaZjflypNe8hbi0+V6VZLxzni14f1Kgs0uie8oH1zNgc+q0Qw9JU/2CnJUCQ92XabHz4HVuQPvFv+4Fv0s+t1hPRZ29MmWPUJ1LGn7fFFk6Mhpz1QAmkvI+mYSMmcMpCY/kiel4l9T2/qNwopMWqFro8VsBsbNNytXDagXD6mywMXVyFVVx6MJo0plHeyXG2bcwCOXWmRJ/RfqOC68PhFmIDCvSVhrluFXqvPpZNUz9QpbNzgd7qrQRoWu9DDr5T4LC24YDs67IbUuwSnl76P5keUXXjenJUMp49kGwpYuMxwJOeDjZYoo66IbiORIrmqfF2nvF64Q+YNZwvZq+qQZM1z7Xmp/TE5OjL/AFBLAQIKAAoAAAgAAARdVVSKIflFHwAAAB8AAAAIAAAAAAAAAAAAAAAAAAAAAABtaW1ldHlwZVBLAQIUABQACAgIAARdVVQyugebjwAAAKwAAAALAAAAAAAAAAAAAAAAAEUAAAB0ZXN0LTAxLnR4dFBLAQIUABQAAgAIACN4OlQeDhsL5QAAAHABAAAVAAAAAAAAAAEAIAAAAA0BAAAwMDItdGVzdC1kb2N1bWVudC54bWxQSwECFAAUAAIACABZcFVUPBo1jpABAACQAwAAGQAAAAAAAAABACAAAAAlAgAATUVUQS1JTkYvQVNpQ01hbmlmZXN0LnhtbFBLAQIUABQAAgAIAAl8AlWE4FR9WhAAALsXAAAZAAAAAAAAAAAAIAAAAOwDAABNRVRBLUlORi90aW1lc3RhbXAwMDEudHN0UEsFBgAAAAAFAAUAQAEAAH0UAAAAAA==</dss:Base64Signature>
			</dss:SignatureObject>
		</esor:credential>
	</esor:credentialsSection>
</esor:XAIP>
